### ISSUE TITLE
No file named frag_hindiii_chrALL.dat1

### ISSUE THREAD

**Issue by oldteng** [axelcournac/Repeats_elements#3]
Hello! I'd like to use the program assignment.c, but I can't find the file frag_hindiii_chrALL.dat1 you said in README.

Thanks a lot!

**Comment by axelcournac** [comment]
Hi, I just put the file in the directory data: this file contains the restriction map for human genome and for the restriction enzyme HindIII. By the way, this code is quite old: I suggest you to use python code fragment_attribution.py in the directory [3C_tutorial](https://github.com/axelcournac/3C_tutorial/tree/master/python_codes).
Best,
a

**Comment by oldteng** [comment]
Thank you very much
I still have a problem. I use the data SRR400260.sra you provide. When I run the program convert_HDF5_txt.bh, after running h5dictToTxt.py I get 11 output files named chrms1, chrms2, cuts1, cuts2, ids1, ids2, misc, seqs1, seqs2, strands1, strands2. Except the file misc, all of the other 10 files are only  2 bytes large and only have a pair of '[' and ']' in it. The file misc contains strings 

> {'genome': {'label2idx': {'chrY': 24, 'chrX': 23, 'chr13': 13, 'chr12': 12, 'chr11': 11, 'chr10': 10, 'chr17': 17, 'chr16': 16, 'chr15': 15, 'chr14': 14, 'chrM': 0, 'chr18': 18, 'chr19': 19, 'chr22': 22, 'chr20': 20, 'chr21': 21, 'chr7': 7, 'chr6': 6, 'chr5': 5, 'chr4': 4, 'chr3': 3, 'chr2': 2, 'chr1': 1, 'chr9': 9, 'chr8': 8}, 'idx2label': {0: 'chrM', 1: 'chr1', 2: 'chr2', 3: 'chr3', 4: 'chr4', 5: 'chr5', 6: 'chr6', 7: 'chr7', 8: 'chr8', 9: 'chr9', 10: 'chr10', 11: 'chr11', 12: 'chr12', 13: 'chr13', 14: 'chr14', 15: 'chr15', 16: 'chr16', 17: 'chr17', 18: 'chr18', 19: 'chr19', 20: 'chr20', 21: 'chr21', 22: 'chr22', 23: 'chrX', 24: 'chrY'}}}

In addition, there is no file named rfragIdxs1 and rfragIdx2.
If I paste all the files I get, I get an output_alignment_idpt.dat like this:

> []      []      []      []      []      []      []      []      []      []      {'genome': {'label2idx': {'chrY': 24, 'chrX': 23, 'chr13': 13, 'chr12': 12, 'chr11': 11, 'chr10': 10, 'chr17': 17, 'chr16': 16, 'chr15': 15, 'chr14': 14, 'chrM': 0, 'chr18': 18, 'chr19': 19, 'chr22': 22, 'chr20': 20, 'chr21': 21, 'chr7': 7, 'chr6': 6, 'chr5': 5, 'chr4': 4, 'chr3': 3, 'chr2': 2, 'chr1': 1, 'chr9': 9, 'chr8': 8}, 'idx2label': {0: 'chrM', 1: 'chr1', 2: 'chr2', 3: 'chr3', 4: 'chr4', 5: 'chr5', 6: 'chr6', 7: 'chr7', 8: 'chr8', 9: 'chr9', 10: 'chr10', 11: 'chr11', 12: 'chr12', 13: 'chr13', 14: 'chr14', 15: 'chr15', 16: 'chr16', 17: 'chr17', 18: 'chr18', 19: 'chr19', 20: 'chr20', 21: 'chr21', 22: 'chr22', 23: 'chrX', 24: 'chrY'}}}

I don't think it is the file I need. Hoping for your help. Thanks a lot.

**Comment by axelcournac** [comment]
If you do not have any information in the files chrms1, chrms2, cuts1 
etc, it means your alignment did not work.

Are you sure you have the library hiclib correctly installed?

Best,

**Comment by oldteng** [comment]
I have solved the problem by re-index the genome. This time, the program can successfully trans chrms1, chrms2, cuts1, cuts2, downsites1, downsites2 to txt file, but when processing ids1 it returns

> ('saving numpy array', u'chrms1', 'to', u'/node19_Disk2/work/HiCtest/bank_less/tmp/chrms1')
(u'/node19_Disk2/work/HiCtest/bank_less/tmp/chrms1', '\t', array([ 5,  1, -1, ...,  7,  6,  7], dtype=int8), '\n')
('saving numpy array', u'chrms2', 'to', u'/node19_Disk2/work/HiCtest/bank_less/tmp/chrms2')
(u'/node19_Disk2/work/HiCtest/bank_less/tmp/chrms2', '\t', array([ 5,  5,  1, ...,  7,  7, -1], dtype=int8), '\n')
('saving numpy array', u'cuts1', 'to', u'/node19_Disk2/tengxy/work/HiCtest/bank_less/tmp/cuts1')
(u'/node19_Disk2/work/HiCtest/bank_less/tmp/cuts1', '\t', array([ 6482387,  8244095,       -1, ..., 14179275, 18006442, 10866478]), '\n')
('saving numpy array', u'cuts2', 'to', u'/node19_Disk2/work/HiCtest/bank_less/tmp/cuts2')
(u'/node19_Disk2/work/HiCtest/bank_less/tmp/cuts2', '\t', array([ 6481961, 10610798,    52946, ..., 14178607, 31394537,       -1]), '\n')
('saving numpy array', u'downrsites1', 'to', u'/node19_Disk2/work/HiCtest/bank_less/tmp/downrsites1')
(u'/node19_Disk2/work/HiCtest/bank_less/tmp/downrsites1', '\t', array([ 6482385,  8244093,       -1, ..., 14180996, 18006454, 10866635]), '\n')
('saving numpy array', u'downrsites2', 'to', u'/node19_Disk2/work/HiCtest/bank_less/tmp/downrsites2')
(u'/node19_Disk2/work/HiCtest/bank_less/tmp/downrsites2', '\t', array([ 6482385, 10611313,    53110, ..., 14179178, 31394646,       -1]), '\n')
('saving numpy array', u'ids1', 'to', u'/node19_Disk2/work/HiCtest/bank_less/tmp/ids1')
(u'/node19_Disk2/work/HiCtest/bank_less/tmp/ids1', '\t', array(['E00511:82:HFNJVALXX:2:1101:10003:11365',
       'E00511:82:HFNJVALXX:2:1101:10003:13650', '', ...,
       'E00511:82:HFNJVALXX:2:1101:9993:13949',
       'E00511:82:HFNJVALXX:2:1101:9993:6741',
       'E00511:82:HFNJVALXX:2:1101:9993:8499'],
      dtype='|S38'), '\n')
Traceback (most recent call last):
  File "/node19_Disk2/software/mirnylib/mirnylib/h5dictUtils/h5dictToTxt.py", line 93, in <module>
    convertFile(sys.argv[1], sys.argv[2],gz=False)
  File "/node19_Disk2/software/mirnylib/mirnylib/h5dictUtils/h5dictToTxt.py", line 68, in convertFile
    numpy.savetxt(savefile, data)
  File "/node19_Disk2/software/miniconda2/lib/python2.7/site-packages/numpy-1.11.3-py2.7-linux-x86_64.egg/numpy/lib/npyio.py", line 1162, in savetxt
    % (str(X.dtype), format))
TypeError: Mismatch between array dtype ('|S38') and format specifier ('%.18e')

The array at the end of each line is because I add a  print(savefile,'\t',data,'\n') in h5dictToTxt.py. It seems that the file ids1 contains an array of reads name.
And if I use the mapping.py from hiclib, I don't get this error and I also don't get the file named ids1.
